variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "db_subnet_ids" {}
variable "aurora_cluster" {}
variable "multi_az" {}
variable "port" {}
variable "instance_type" {}
variable "engine_version" {}
variable "encryption" {}
variable "maintenance_window" {}
variable "backup_window" {}
variable "backup_retention_period" {}
variable "allow_major_version_upgrade" {}
variable "auto_minor_version_upgrade" {}
variable "deletion_protection" {}
variable "apply_immediately" {}
variable "replica_count" {}
variable "aurora_parameter_group" {}
variable "allocated_storage" {}
variable "max_allocated_storage" {}
variable "storage_type" {}
variable "storage_throughput" {}
variable "parameter_group" {}